### ISSUE TITLE
跨域的问题

### ISSUE THREAD

**Issue by mjiong** [brickspert/wedding-Invitations#1]
`app.use(proxy('/wedding', {
    target: 'http://localhost:80',
    changeOrigin: true
}));`
比如如上代码，target是否是对于的api？/wedding是站点根目录还是？

请原谅我，对webpack不熟悉。

**Comment by brickspert** [comment]
@mjiong 你好，原谅我回复这么迟。过年这段时间在老家。    `http://localhost:80/wedding`指向了API的地址，target是API地址。  这段代码的意思是：遇到`/wedding`，就代理到80端口上~

**Comment by mjiong** [comment]
原谅我的理解能力。比如我的api地址是 www.php.dev
是不是就是这样配置：
`app.use(proxy('/wedding', {
    target: 'www.php.dev',
    changeOrigin: true
}));`

**Comment by brickspert** [comment]
@mjiong 
我举个例子哈~
前端整个项目的运行地址为  `http://frontend.com`。
后端（即API）运行地址为 `http://backend.com`。

那么在前端坏境下，我调用API接口，调用这个地址 `http://frontend.com/api/getBless.php`。那么问题来了，真实的API地址应该是 `http://backend.com/api/getBless.php`。

如何实现呢？这里我们就用到了代理
`app.use(proxy('/api', { target: 'http://www.backend.com', changeOrigin: true }));`
意思就是：URL包含 `/api` 就代理到后端服务器去~

**Comment by mjiong** [comment]
代理这块我还有待自己研究。非常感谢你的回答了。
