### ISSUE TITLE
为什么一直在加载进不去，哪里设置有问题吗

### ISSUE THREAD

**Issue by chankillo** [brickspert/wedding-invitations#5]

**Comment by brickspert** [comment]
@chankillo 你是本地打开的吗？可以截图下报错信息看看。

**Comment by chankillo** [comment]
![image](https://user-images.githubusercontent.com/13761637/32930453-c00ae54c-cb99-11e7-9e9a-587515d79cfc.png) 电脑上打不开，手机上loading

**Comment by chankillo** [comment]
后台没有报错，电脑上访问503

**Comment by chankillo** [comment]
![Uploading image.png…]()  https://brickspert.github.io/wedding-Invitations/

**Comment by chankillo** [comment]
https://brickspert.github.io/wedding-Invitations/
![image](https://user-images.githubusercontent.com/13761637/32930617-b40e12d6-cb9a-11e7-94e4-5d935bfafe89.png)

**Comment by chankillo** [comment]
访问这个地址也不西行

**Comment by brickspert** [comment]
@chankillo 你好，我重新下载了一份代码然后`npm install`，`npm start`,然后直接浏览器打开`http://localhost:8081`是没有问题的呀。
你试试把`webpack.dev.config.js`里面的`publicPath `修改成`http://localhost:8081/`试试。

另外如果你要手机可以访问，这里需要改成局域网ip哦，然后用局域网ip访问。

**Comment by chankillo** [comment]
我重新跑了一下还是不行，需要安装什么环境吗，我现在连你上面的演示地址都打不开

**Comment by chankillo** [comment]
![image](https://user-images.githubusercontent.com/13761637/32931111-66280fb0-cb9d-11e7-914e-64325664cd24.png) 我执行npm install 的时候有警告

**Comment by chankillo** [comment]
我换了台电脑重新跑了一下可以了，现在还不知道原因，非常感谢，以后有问题再咨询

**Comment by brickspert** [comment]
@chankillo 我的那个链接打不开没关系的。哈哈，

你这个问题，我这么看也看不出来。要不晚上我帮你远程调试一下。
